backend:
  name: git-gateway
media_folder: "assets/img"
public_folder: "/assets/img"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "overlay", name: "overlay", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image", required: true }
      - { label: "herp", name: "herp", widget: "herp", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
